Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('',include('account.urls'))
]

account/urls.py
from django.urls import path
from . import views

app_name = 'accounts' 

urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('login_view/',views.login_view,name='login'),
    path('logout_view/',views.logout_view,name='logout'),
]

myapp/urls.py
from django.urls import path
from . import views

app_name = 'todo'


urlpatterns = [
    path('',views.home,name='home'),
    path('create_todo/',views.create_todo,name='create_todo'),
    path('todo_details/<int:pk>/',views.todo_details,name='todo_details'),
    path('todo_update/<int:pk>/',views.update_todo,name='todo_update'),
    path('todo_delete/<int:pk>/',views.delete_todo,name='todo_delete'),
]

account/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.forms import ModelForm

class RegisterForm(forms.ModelForm):
    username = forms.CharField(required=True,
    widget = forms.TextInput(
        attrs={
            'placeholder':'Enter Username',
            'class':'form-control'
        }
    )) 

    email=forms.EmailField(required=True,
    widget = forms.TextInput(
        attrs={
            'placeholder':'Enter Email',
            'class':'form-control'
        }
    ))

    password=forms.CharField(required=True,
    widget = forms.TextInput(
        attrs={
            'placeholder':'Enter Password',
            'class':'form-control'
        }
    ))

    confirm_password=forms.CharField(required=True,
    widget = forms.TextInput(
        attrs={
            'placeholder':'Re-enter Password',
            'class':'form-control'
        }
    ))
    class Meta:
        model= User
        fields=['username','email','password']


class LoginForm(forms.ModelForm):
    email=forms.EmailField(required=True,
    widget = forms.TextInput(
        attrs= {
            'placeholder':'Enter Email',
            'class':'form-control'
        }
    ))

    password=forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Enter Password',
                'class':'form-control'
            }
        )
    )

    
    class Meta:
        model= User
        fields=['email','password']

myapp/forms.py
from django import forms
from .model.task import Task

class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','description','complete']
        widgets = {
            'user':forms.Select(attrs={'class':'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter title'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
            'completed': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

account/views.py
from django.shortcuts import render,redirect
from account.forms import RegisterForm,LoginForm
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from myapp.views import home
from django.urls import reverse



# Create your views here.


# def register(request):
#     form = RegisterForm()
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
#                 messages.error(_(request,"Password fields don't match"))
#             else:
#                 user = User.objects.create_user(
#                     username=form.cleaned_data['username'],
#                     email=form.cleaned_data['email'],
#                     password=form.cleaned_data['password'],
#                     confirm_password=form.cleaned_data['confirm_password']
#                 )
#                 user.save()
#                 messages.success(_(request,f'Account created for {user.username}!!'))
#                 return redirect('user_account:login')
#         return messages.error(request,_('Registration failed, Enter correct details'))
#     form=RegisterForm()
#     return render(request,'auth/register.html',{'form':form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            if password != confirm_password:
                messages.error(request, _("Password fields don't match"))
            else:
                user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password'],  # Use the cleaned password
                )
                user.save()
                messages.success(request, f'Account created for {user.username}!!')
                return redirect('accounts:login')
        else:
            messages.error(request, _('Registration failed. Please enter correct details.'))
    else:
        form = RegisterForm()
    return render(request, 'auth/register.html', {'form': form})

def login_view(request):
    form = LoginForm()
    if request.method =='POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)
                user.save() 
                messages.success(request, _( "You have logged in Successfully!"))
                return redirect(reverse('todo:home'))
            else:
                messages.error(request, _("Invalid Email or Password Provided"))
        form=LoginForm(request.POST)
    return render(request,'auth/login.html',{'form':form})



def logout_view(request):
    logout(request)
    return render(request,'auth/logout.html')

myapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from myapp.model.task import Task
from .forms import TodoForm
from django.http import Http404

# Create your views here.
def home(request):
    Tasks = Task.objects.all()
    search_input = request.GET.get('search-area') or ''
    if search_input:
        Tasks = Tasks.filter(title__startswith=search_input)
        #To filter using the first letters, use "title_startswith not icontains" 
    context = {'Tasks':Tasks,'search_input':search_input}
    return render(request,'todo/home.html',context)

def todo_details(request,pk):
    try:
        Tasks = Task.objects.get(pk=pk)
    except Task.DoesNotExist:
        raise Http404("Task is Unavailable")
    context ={'Tasks':Tasks}
    return render(request,'todo/todo-details.html',context)

def create_todo(request):
    form = TodoForm()
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:home')
        TodoForm()
    context = {'form':form}
    return render(request,'todo/create_todo.html',context) 

def update_todo(request,pk):
    todo = Task.objects.get(pk=pk)
    form= TodoForm(instance=todo)
    if request.method == 'POST':
        form = TodoForm(request.POST,instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todo:home')
        TodoForm()
    context = {'form':form}
    return render(request,'todo/update_todo.html',context)

def delete_todo(request,pk):
    delete = get_object_or_404(Task,pk=pk)
    if request.method == 'POST':
        delete.delete()
        return redirect('todo:home')
    context={'delete':delete}
    return render(request,'todo/delete_todo.html',context)

myapp/templates/todo/home.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>TodoListApp</title>
  <meta name="description" content="Todo List App. For staying more organinsed and disciplined">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<style type="text/css">
  .action-btns{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }
  .add{
    margin-left: 600px;
  }
  .main{
    width: 800px;
  }
  .card-body{
    margin-right: 200px;
  }
  a{
    text-decoration: none;
    
  }
</style>
</head>
<body>

	<section class="vh-100" style="background-color: #eee; ">
        <div class="container py-5 h-100"style='width: 1500px;'>
            <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card rounded-3 main" >
                <div class="card-body p-4 main">
                  {% if request.user.is_authenticated %}
                  <p>Hello User</p>
                  <a href="{% url 'todo:logout' %}">Logout</a>
                  {% else %}
                  <a href="{% url 'todo:login' %}">Login</a>
                  {% endif %}
                    <h4 class="text-center my-3 pb-3">TODO LIST APP</h4>
                    <form action="" method="get" class="search-form">
                      <input type="text" name="search-area">
                      <input type="submit" value="Search">

                    </form>

                    
                    <div class="col-3 add">
                        <a href="{% url 'todo:create_todo' %}"  class="btn btn-primary">Add Todo</a>
                    </div> 
                    <table class="table mb-4">
                    <thead>
                        <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Task name</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for task in Tasks %}
                            <tr>
                                {% if task.done %}
                                <td scope='row'>{{forloop.counter}}</td>
                                <a href='{% url "todo:todo_details" pk=todo_details.pk %}'><td>{{task.title}}</td></a>
                                {% else %}
                                <td scope='row'>{{forloop.counter}}</td>
                                <td><a href='{% url "todo:todo_details" task.pk %}'>{{task.title}}</a></td>

                                <td>
                                    {% if task.complete %}
                                      Completed
                                    {% else %}
                                      In Progress
                                    {% endif %}
                                </td>
                                <td>
                                    
                                    {% comment %} <div class="action-btns"> {% endcomment %}
                                        <a href='{% url "todo:todo_delete" task.pk %}'><button type="submit" class="btn btn-danger">&#215;</button></a>
                                        <a href='{% url "todo:todo_details" task.pk %}'><button type="submit" class="btn btn-danger">&#8858;</button></a>
                                        <button type="submit" class="btn btn-success ms-1">&#10003;</button>
                                        <a href='{% url "todo:todo_update" task.pk %}'><button type="submit" class="btn btn-primary ms-1">&#8608;</button></a>
                                    {% comment %} </div> {% endcomment %}
                                </td>

                                {% endif %}
                                {% comment %} <h3>No Tasks Available</h3> {% endcomment %}
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>

                </div>
                </div>
            </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/todo/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>TodoListApp</title>
  <meta name="description" content="Todo List App. For staying more organinsed and disciplined">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <style>
        body{
            background-color: rgba(228, 221, 221, 0.993);
            padding-top: 50px;
        }
        .container{
            max-width: 550px;
            margin: auto;
            background-color: whitesmoke;
            
        }
        .text-area{
            border: 1px solid #eb796f;
            border-radius: 5%;
            padding: 10px;
            width: 90%;
        }
        form{
            border: 1px solid #eb796f;
            border-radius: 5%;
            padding: 10px;
            width: 90%;
        }
    </style>
</head>
<body>
    <div class="container">
        {% block page %}
        
        {% endblock page %}


    </div>
</body>
</html>

templates/todo/create_todo.html
{% load static %}

<style>
    body{
        background-color: rgba(228, 221, 221, 0.993);
        padding-top: 50px;
    }
    form{
        height:500px;
        max-width: 590px;
        margin: auto;
        background-color: whitesmoke;
        
    }
    .form-control {
        width: 70%; /* Adjust the width as needed */
        padding: 10px;
        margin-top: 50px;
        border: 1px solid #ccc;
        border-radius: 5px; 
        box-sizing: border-box;
    }
    
    
</style>
<a href='{% url "todo:home" %}'>Back</a>
<div class='form-container'>
    <form method="POST" action="" class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Create Todo</button>
    </form> 
</div>

templates/todo/delete_todo.html
{% extends "todo/base.html" %}
{% block page %}
<style>
    a{
        text-decoration:none;
    }
</style>
<form method='POST'>
    {% csrf_token %}
    <h4>Are You sure You want to delete "{{delete.title}}" ?</h4>
    <input type='submit' value='Delete'>
    <a href='{% url "todo:home" %}'><button type="submit" class="btn btn-success ms-1">No</a>
</form>
{% endblock page %}

templates/todo/home.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>TodoListApp</title>
  <meta name="description" content="Todo List App. For staying more organinsed and disciplined">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<style type="text/css">
  .action-btns{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }
  .add{
    margin-left: 600px;
  }
  .main{
    width: 800px;
  }
  .card-body{
    margin-right: 200px;
  }
  a{
    text-decoration: none;
    
  }
</style>
</head>
<body>

	<section class="vh-100" style="background-color: #eee; ">
        <div class="container py-5 h-100"style='width: 1500px;'>
            <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card rounded-3 main" >
                <div class="card-body p-4 main">
                  {% if user.is_authenticated %}
                    <p>Hello User</p> 
                    <a href="{% url 'accounts:register' %}">Logout</a>
                  {% else %}
                    <a href="{% url 'accounts:login' %}">Login</a>
                    <a href="{% url 'accounts:register' %}">Register</a>
                  {% endif %}
                    <h4 class="text-center my-3 pb-3">TODO LIST APP</h4>
                    <form action="" method="get" class="search-form">
                      <input type="text" name="search-area">
                      <input type="submit" value="Search">

                    </form>

                    
                    <div class="col-3 add">
                        <a href="{% url 'todo:create_todo' %}"  class="btn btn-primary">Add Todo</a>
                    </div> 
                    <table class="table mb-4">
                    <thead>
                        <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Task name</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for task in Tasks %}
                            <tr>
                                {% if task.done %}
                                <td scope='row'>{{forloop.counter}}</td>
                                <a href='{% url "todo:todo_details" pk=todo_details.pk %}'><td>{{task.title}}</td></a>
                                {% else %}
                                <td scope='row'>{{forloop.counter}}</td>
                                <td><a href='{% url "todo:todo_details" task.pk %}'>{{task.title}}</a></td>

                                <td>
                                    {% if task.complete %}
                                      Completed
                                    {% else %}
                                      In Progress
                                    {% endif %}
                                </td>
                                <td>
                                    
                                    {% comment %} <div class="action-btns"> {% endcomment %}
                                        <a href='{% url "todo:todo_delete" task.pk %}'><button type="submit" class="btn btn-danger">&#215;</button></a>
                                        <a href='{% url "todo:todo_details" task.pk %}'><button type="submit" class="btn btn-danger">&#8858;</button></a>
                                        <button type="submit" class="btn btn-success ms-1">&#10003;</button>
                                        <a href='{% url "todo:todo_update" task.pk %}'><button type="submit" class="btn btn-primary ms-1">&#8608;</button></a>
                                    {% comment %} </div> {% endcomment %}
                                </td>

                                {% endif %}
                                {% comment %} <h3>No Tasks Available</h3> {% endcomment %}
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>

                </div>
                </div>
            </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/todo/todo-details.html
{% extends "todo/base.html" %}
{% block page %}

<h3>Task:</h3>
    {{Tasks.title}}

    <h3>Description:</h3>
    {% if Tasks.description %}
        {{Tasks.description}}
    {% else %}
        No description Provided 
    {% endif %}

    <h3>Status:</h3>
    {% if Tasks.complete %}
        Completed
    {% else %}
        In Progress
    {% endif %}
{% endblock page %}

templates/todo/update_todo.html
{% load static %}

<style>
    .form-control {
        width: 30%; /* Adjust the width as needed */
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px; 
        box-sizing: border-box;
    }
    .form{
        margin-left:10px
        
    }
    .form-container{
        margin-left:59px;
    }
</style>
<a href='{% url "todo:home" %}'>Back</a>
<div class='form-container'>
    <form method="POST" action="" class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save Updates</button>
    </form> 
</div>